### ISSUE TITLE
[investigate downstream breakchange first] inconsistency of argument `flag_variables` in `s_count_patients_with_flags`

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/tern#910] opened 2023-05-11 07:39 UTC
https://github.com/insightsengineering/tern/blob/7fe98a0490e1546dd37cfeb86b5e6237505ed345/R/count_patients_with_event.R#L212

see the following example

```{r}
library(tern)
library(rtables)
adae <- tern_ex_adae %>%
  mutate(
    fl1 = TRUE,
    fl2 = TRTEMFL == "Y",
    fl3 = TRTEMFL == "Y" & AEOUT == "FATAL",
    fl4 = TRTEMFL == "Y" & AEOUT == "FATAL" & AEREL == "Y"
  )
labels <- c(
  "fl1" = "Total AEs",
  "fl2" = "Total number of patients with at least one adverse event",
  "fl3" = "Total number of patients with fatal AEs",
  "fl4" = "Total number of patients with related fatal AEs"
)
formatters::var_labels(adae)[names(labels)] <- labels

s_count_patients_with_flags(
  adae,
  "SUBJID",
  flag_variables = c("fl1", "fl2", "fl3", "fl4"),
  denom = "N_col",
  .N_col = 1000
)

s_count_patients_with_flags(
  adae,
  "SUBJID",
  flag_variables = c("fl1" = 'a', "fl2" = 'v', "fl3" = 'c', "fl4" = 'd'),
  denom = "N_col",
  .N_col = 1000
)
```

apparently, the latter case, we switch the "variable" and "name". the meaning of the argument, `flag_variables` is totally changed.

if we don't give name to a character vector, its still have the values. if we give names to it, then its values became the labels, and its labels become the variables analyzed. this is confusing I have to say, as giving a vector name should not change its attribute as a character vector (which means that the values, instead of the names, should be used in analyze!)

**Comment by shajoezhu** [comment] 2023-06-21 01:39
Investigate downstream break change first

**Comment by Melkiades** [comment] 2023-07-07 16:42
I checked it and this is expected behavior. `flag_variables` is and should be a character vector and it is not important if it is named or not. The two vectors provided in the example produce different results because they use different character vectors. The function itself is doing something weird with naming, I agree, but it is still doing it in that scoping, so it should not affect the input variable. I tested this too.
```
> flag_variables = c("fl1", "fl2", "fl3", "fl4")
> flag_variables2 = c("fl1" = 'a', "fl2" = 'v', "fl3" = 'c', "fl4" = 'd')
> flag_variables
[1] "fl1" "fl2" "fl3" "fl4"
> flag_variables2
fl1 fl2 fl3 fl4 
"a" "v" "c" "d" 
```
I hope I did not misunderstand the question, but for now, I am closing this issue (added a check for character vector).

**Comment by edelarua** [comment] 2023-07-07 21:55
@Melkiades since this function has very confusing label handling, I want to propose the changes in https://github.com/insightsengineering/tern/pull/1005 which would allow for more intuitive labelling while still supporting the current method (no downstream breakages). What do you think?

**Closed** 2023-07-08 17:03 UTC
Labels: research, sme

**Comment by clarkliming** [comment] 2023-07-10 01:53
> I checked it and this is expected behavior. `flag_variables` is and should be a character vector and it is not important if it is named or not. The two vectors provided in the example produce different results because they use different character vectors. The function itself is doing something weird with naming, I agree, but it is still doing it in that scoping, so it should not affect the input variable. I tested this too.
> 
> ```
> > flag_variables = c("fl1", "fl2", "fl3", "fl4")
> > flag_variables2 = c("fl1" = 'a', "fl2" = 'v', "fl3" = 'c', "fl4" = 'd')
> > flag_variables
> [1] "fl1" "fl2" "fl3" "fl4"
> > flag_variables2
> fl1 fl2 fl3 fl4 
> "a" "v" "c" "d" 
> ```
> 
> I hope I did not misunderstand the question, but for now, I am closing this issue (added a check for character vector).

well this behavior, is making the input variable, very confusing. while `flag_variables` is using its value as the variable to analyze, `flag_variables2` is using its `names` as variables to analyze. 

We can say that this is expected, but it really does not make sense: adding vector names will lead to errors.
