### ISSUE TITLE
[Failed to install tern package]: <Failed to install tern package in 4.1.2 R version.>

### ISSUE THREAD

**Issue by chengzhang96** [insightsengineering/tern#1217] opened 2024-03-29 10:40 UTC
### What is your question?

My R version is 4.1.2, when I try to install the tern package, it tells me that the dependency package "estimability" requires R (>= 4.3.0), is there any way for me to successfully install the tern package in R version 4.1.2?
![屏幕截图 2024-03-29 182956](https://github.com/insightsengineering/tern/assets/126157730/3a381fc6-9e00-410c-80c5-346c33da75c0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment] 2024-04-02 07:19
@pawelru do we then need tern R>4.3? Maybe it is a dependency we can have a lower minimum version?

**Comment by chengzhang96** [comment] 2024-04-02 08:29
library(devtools)
install_version("estimability", version = "1.4.1")

I can now successfully install the tern package by installing v1.4.1 of estimability

**Comment by pawelru** [comment] 2024-04-02 08:35
> @pawelru do we then need tern R>4.3? Maybe it is a dependency we can have a lower minimum version?

We definitely don't. It's due to external dependency that is out of our control. Luckily OP managed to find the root cause and find a work around. I think it's fair to close it.

**Closed by pawelru** 2024-04-02 08:35 UTC
Labels: question
